### ISSUE TITLE
Locale not supported by C library. Using the fallback 'C' locale.

### ISSUE THREAD

**Issue by zty199** [Dziban-dev/dde-appknitter#2]
My system language is Simplified Chinese. When I run the appknitter.sh directly, it shows this error in terminal: "Locale not supported by C library. Using the fallback 'C' locale."

I find out that I need to modify /etc/default/locale to make it work. I follow the instruction in this blog: https://blog.csdn.net/rovast/article/details/78293746 .

This is what /etc/default/locale is written by default:

LANG=zh_CN.UTF-8
LANGUAGE=zh_CN

and after the modification, the script works:

LANG=en_US.UTF-8
LANGUAGE=zh_CN.utf8
LC_ALL=zh_CN.utf8

Is there any solution for this weird problem?

**Comment by zty199** [comment]
Find out a new solution...... In appknitter.sh, add "export LC_ALL=zh_CN.UTF-8" behind #!/bin/bash, and problem solved, everything works just fine. Though I don't know how it works......

**Comment by Dziban-dev** [comment]
Hi, thanks for the report. would you like to test version 1.2 ? see if it fixes the issue. thanks.

**Comment by zty199** [comment]
I've tested version 1.2. Seems that the issue has been fixed and everthing works fine now. Thank you.
